// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoreoWeb.Data;

#nullable disable

namespace MonitoreoWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoreoWeb.Models.ChecklistRecepcion", b =>
                {
                    b.Property<int>("IdChecklist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChecklist"));

                    b.Property<bool>("AltavozMicOk")
                        .HasColumnType("bit");

                    b.Property<bool>("BotonesFuncionan")
                        .HasColumnType("bit");

                    b.Property<bool>("CamaraFrontalOk")
                        .HasColumnType("bit");

                    b.Property<bool>("CamaraTraseraOk")
                        .HasColumnType("bit");

                    b.Property<bool>("CargaCorrectamente")
                        .HasColumnType("bit");

                    b.Property<bool>("Enciende")
                        .HasColumnType("bit");

                    b.Property<string>("FirmaClienteBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HumedadOAgua")
                        .HasColumnType("bit");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int");

                    b.Property<bool>("LeeSIM")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("PantallaEstrellada")
                        .HasColumnType("bit");

                    b.Property<bool>("RayonesVisibles")
                        .HasColumnType("bit");

                    b.Property<bool>("TapaTraseraDañada")
                        .HasColumnType("bit");

                    b.HasKey("IdChecklist");

                    b.HasIndex("IdReparacion")
                        .IsUnique();

                    b.ToTable("ChecklistRecepcion", (string)null);
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Dispositivo", b =>
                {
                    b.Property<int>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDispositivo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("IdCliente");

                    b.ToTable("Dispositivo", (string)null);
                });

            modelBuilder.Entity("MonitoreoWeb.Models.FotoAvance", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAvance")
                        .HasColumnType("int");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VisibleCliente")
                        .HasColumnType("bit");

                    b.HasKey("IdFoto");

                    b.HasIndex("IdAvance");

                    b.HasIndex("IdReparacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FotoAvance", (string)null);
                });

            modelBuilder.Entity("MonitoreoWeb.Models.HistorialAvance", b =>
                {
                    b.Property<int>("IdAvance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvance"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdAvance");

                    b.HasIndex("IdReparacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("HistorialAvance", (string)null);
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdReparacion");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Reparacion", b =>
                {
                    b.Property<int>("IdReparacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReparacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiasGarantia")
                        .HasColumnType("int");

                    b.Property<bool>("EsGarantia")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaEntregaCliente")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTerminacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaAdminEntregaBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDispositivo")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdReparacionOriginal")
                        .HasColumnType("int");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemaReportado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReparacion");

                    b.HasIndex("IdDispositivo");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reparacion", (string)null);
                });

            modelBuilder.Entity("MonitoreoWeb.Models.TokenConsulta", b =>
                {
                    b.Property<int>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdToken"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int");

                    b.HasKey("IdToken");

                    b.HasIndex("IdReparacion");

                    b.ToTable("TokenConsulta");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("MonitoreoWeb.Models.ChecklistRecepcion", b =>
                {
                    b.HasOne("MonitoreoWeb.Models.Reparacion", "Reparacion")
                        .WithOne("Checklist")
                        .HasForeignKey("MonitoreoWeb.Models.ChecklistRecepcion", "IdReparacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparacion");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Dispositivo", b =>
                {
                    b.HasOne("MonitoreoWeb.Models.Cliente", null)
                        .WithMany("Dispositivos")
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("MonitoreoWeb.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.FotoAvance", b =>
                {
                    b.HasOne("MonitoreoWeb.Models.HistorialAvance", "Avance")
                        .WithMany("Fotos")
                        .HasForeignKey("IdAvance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoreoWeb.Models.Reparacion", "Reparacion")
                        .WithMany()
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoreoWeb.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avance");

                    b.Navigation("Reparacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.HistorialAvance", b =>
                {
                    b.HasOne("MonitoreoWeb.Models.Reparacion", "Reparacion")
                        .WithMany()
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoreoWeb.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Pago", b =>
                {
                    b.HasOne("MonitoreoWeb.Models.Reparacion", "Reparacion")
                        .WithMany("Pagos")
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparacion");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Reparacion", b =>
                {
                    b.HasOne("MonitoreoWeb.Models.Dispositivo", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonitoreoWeb.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IdTecnico");

                    b.HasOne("MonitoreoWeb.Models.Usuario", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Dispositivo");

                    b.Navigation("Tecnico");

                    b.Navigation("UsuarioCrea");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.TokenConsulta", b =>
                {
                    b.HasOne("MonitoreoWeb.Models.Reparacion", "Reparacion")
                        .WithMany("Tokens")
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparacion");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Cliente", b =>
                {
                    b.Navigation("Dispositivos");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.HistorialAvance", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("MonitoreoWeb.Models.Reparacion", b =>
                {
                    b.Navigation("Checklist");

                    b.Navigation("Pagos");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
